The aim of the script is to get the FY assigned to the TPI MQ indicators. This takes the highest count of the years made available from the documents.

This script requires the download of RCs to estimate the FY.

In [1]:
import pandas as pd
import numpy as np
import getpass
user = getpass.getuser()
from datetime import date
import datetime as dt
from datetime import datetime
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

Run the SQL Climate_SID_Extract_31_May_2023.sql and update the SQL row 87 and 200 for the correct RC numbers.
Note that later RC do not need updates but later ones possibly.

SQL file located here:

Load in the files we use low_money for the size of the files

In [3]:

location = 'C://Users//U6089306//OneDrive - London Stock Exchange Group//TPI_MQ//File//RC//'    

file = 'RC9Extract.csv'
df5 = pd.read_csv(location +file, low_memory=False)

file = 'RC10Extract_20_05_24.csv'
df4 = pd.read_csv(location +file, low_memory=False)

file = 'RC8Extract.csv'
df3 = pd.read_csv(location +file, low_memory=False)

file = 'RC7Extract.csv'
df2 = pd.read_csv(location +file, low_memory=False)

file = 'RC6Extract.csv'
df1 = pd.read_csv(location +file, low_memory=False)

file = 'RC5Extract.csv'
df0 = pd.read_csv(location +file, low_memory=False)

We concate the files together into a large dataframe then remove the prior dataframes to save memory

In [4]:
all_dfs = [df0, df1, df2,df3,df4,df5]
df = pd.concat(all_dfs).reset_index(drop=True)

del(df0)
del(df1)
del(df2)
del(df3)
del(df4)
del(df5)

In [39]:
sample =df[( df['ResearchId'] ==26328)]
sample.head(5)

,ISIN,SEDOL,FTSE_ID,PrimeEntityId,CompanyId,ResearchId,ResearchStageId,ResearchStage,WebUrl,acronym,seqnum,SubIndicatorCode,Question,PeriodEndDate,ResearchCycleId,ResearchCycle,ResponseComments,SourceText,LastChangedOnDateUTC,ResponseType,ResponseNumber,ResponseText,ConversionRatio,Unit,ResponseNumberScaled,DocRef1Id,DocRef1Name,Ref1Category,Ref1PageNo,DocRef1FilingDate,DocRef1Year,DocRef1StartDate,DocRef1EndDate,DocRef2Id,DocRef2Name,Ref2Category,Ref2PageNo,DocRef2FilingDate,DocRef2Year,DocRef2StartDate,DocRef2EndDate,CommentsToQC
533382,CLP249051044,2196189,1205310,109043.0,8940,26328,16,Published,http://www.ccu.cl,ECC01,1,ECC01_1,a) Address the issue,2020-12-15 08:48:02.100,7,ESG 2020-2021,[OPTION A]+[OPTION B]: Our commitment to the p...,[OPTION A]+[OPTION B]: Nuestro compromiso con ...,2020-07-21 05:15:30.940,Yes/No,NaN,Yes,NaN,NaN,NaN,300989.0,Sustainability Report (Spanish) 2018,CR Report,76,2020-07-20 08:12:14.377,2018.0,2018-01-01 00:00:00.000,2018-12-31 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533383,CLP249051044,2196189,1205310,109043.0,8940,26328,16,Published,http://www.ccu.cl,ECC01,2,ECC01_2,b) Reduce or avoid the impact or improve effic...,2020-12-15 08:48:02.100,7,ESG 2020-2021,[OPTION A]+[OPTION B]: Our commitment to the p...,[OPTION A]+[OPTION B]: Nuestro compromiso con ...,2020-07-21 05:15:30.940,Yes/No,NaN,Yes,NaN,NaN,NaN,300989.0,Sustainability Report (Spanish) 2018,CR Report,76,2020-07-20 08:12:14.377,2018.0,2018-01-01 00:00:00.000,2018-12-31 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533384,CLP249051044,2196189,1205310,109043.0,8940,26328,16,Published,http://www.ccu.cl,ECC03,1,ECC03_1,a) Membership of business associations,2020-12-15 08:48:02.100,7,ESG 2020-2021,[Company Feedback]: C: Data gap / Error Correc...,[OPTION A]: CCU firma Acuerdo de Producci√≥n L...,2020-09-09 12:11:40.143,Yes/No,NaN,Yes,NaN,NaN,NaN,300968.0,Annual Report (Spanish) 2019,Annual Report or equivalent,59,2020-07-20 07:43:49.360,2019.0,2019-01-01 00:00:00.000,2019-12-31 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clean Production Agreement -Ecolabelling (evid...
533385,CLP249051044,2196189,1205310,109043.0,8940,26328,16,Published,http://www.ccu.cl,ECC03,2,ECC03_2,b) Company position on public policy and regul...,2020-12-15 08:48:02.100,7,ESG 2020-2021,[Company Feedback]: C: Data gap / Error Correc...,[OPTION A]: CCU firma Acuerdo de Producci√≥n L...,2020-09-09 12:11:40.143,Yes/No,NaN,No,NaN,NaN,NaN,300968.0,Annual Report (Spanish) 2019,Annual Report or equivalent,59,2020-07-20 07:43:49.360,2019.0,2019-01-01 00:00:00.000,2019-12-31 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Clean Production Agreement -Ecolabelling (evid...
533386,CLP249051044,2196189,1205310,109043.0,8940,26328,16,Published,http://www.ccu.cl,ECC05,1,ECC05_1,a) Company mentions addressing adaptation,2020-12-15 08:48:02.100,7,ESG 2020-2021,[OPTION A]: CCU supports Study of Adaptation t...,[OPTION A]: CCU apoya Estudio de Adaptaci√≥n a...,2020-07-21 05:30:20.767,Yes/No,NaN,Yes,NaN,NaN,NaN,300970.0,Sustainability Report (Spanish) 2019,CR Report,60,2020-07-20 07:45:17.573,2019.0,2019-01-01 00:00:00.000,2019-12-31 00:00:00.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

this is a list of the codes used in TPI MQ we want to filter for these

In [11]:
tpi_list = [
'ECC01',  'ECC03',  'ECC05',
'ECC08',  'ECC14',  'ECC15',  'ECC19',
'ECC23',  'ECC31',  'ECC32',  'ECC38',
'ECC39',  'ECC41',  'ECC42',  'ECC43',  
'ECC44',  'ECC45',
'ECC48',  'ECC49',  'ECC50',  'ECC51',
'ECC56',  'ECC57',  'ECC60',  'ECC73',
'ECC74',  'ECC75',  'ECC76',  'ECC77',
'ECC78',  'EPR18',  'EPR19',  'EPR21',
'ESC31']

tpi = df[df['acronym'].isin(tpi_list)]

In [12]:
##keeping this for reference extract year from Doc Ref Name
# tpi['year_of_DocRef1Name']=tpi['DocRef1Name'].str.extract('(\d+)')
# tpi['year_of_DocRef2Name']=tpi['DocRef2Name'].str.extract('(\d+)')
tpi.tail(10)

,ISIN,SEDOL,FTSE_ID,PrimeEntityId,CompanyId,ResearchId,ResearchStageId,ResearchStage,WebUrl,acronym,...,DocRef1EndDate,DocRef2Id,DocRef2Name,Ref2Category,Ref2PageNo,DocRef2FilingDate,DocRef2Year,DocRef2StartDate,DocRef2EndDate,CommentsToQC
2494589,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC75,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494590,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC76,...,NaN,553274.0,TCFD Report 2022,Other Report,1,2023-02-08 08:36:41.187,2022.0,NaN,NaN,NaN
2494591,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC76,...,NaN,553274.0,TCFD Report 2022,Other Report,1,2023-02-08 08:36:41.187,2022.0,NaN,NaN,NaN
2494592,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC76,...,NaN,553274.0,TCFD Report 2022,Other Report,1,2023-02-08 08:36:41.187,2022.0,NaN,NaN,NaN
2494593,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494594,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494595,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC77,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494596,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494597,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2494598,ZAE000325783,BN0VX82,1209519,NaN,9330,41790,16,Published,http://www.naspers.com,ECC78,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
def time_format (df,col,new_col):
    df[new_col] = pd.to_datetime(df[col], format='%Y-%m-%d %H:%M:%S.%f', errors='coerce')
    return df

def time_year (df,col,new_col):
    df[new_col] = df[col].dt.year
    return df

#this sectonr filters out CDP, TCFD and TPI values as we want to get the company reported documents
def filter_col (df,col_cat,col_name):
    df=df[~df[col_name].str.contains('CDP', na=False)]           
    df=df[~df[col_cat].str.contains('CDP', na=False)] 
    df=df[~df[col_name].str.contains('TCFD', na=False)]           
    df=df[~df[col_cat].str.contains('TCFD', na=False)] 
    df=df[~df[col_name].str.contains('TPI', na=False)]           
    df=df[~df[col_cat].str.contains('TPI', na=False)] 
    return df

#tjos group by 
def group (df,RC,FTSE_ID,RI,fmt_date,year):
    df=data.groupby([RC,FTSE_ID,RI,fmt_date,year]
             ).size().sort_values().groupby(level=2).tail(1).reset_index()
    return df

Order of checks starts from DocRef1EndDate, DocRef2EndDate, DocRef1FilingDate then DocRef2FilingDate.

In [14]:
data = tpi
data = time_format(data,'DocRef1EndDate','fmt_DocRef1EndDate')
data = time_year(data,'fmt_DocRef1EndDate','year(DocRef1EndDate)')
data = filter_col(data,'Ref1Category','DocRef1Name')

TPI_Ref_2 = group(data,'ResearchCycleId','FTSE_ID','ResearchId','fmt_DocRef1EndDate','year(DocRef1EndDate)')

TPI_Ref_2=TPI_Ref_2.rename(columns={"fmt_DocRef1EndDate": "Date","year(DocRef1EndDate)":"Year(Date)"})
TPI_Ref_2['Method']= 'DocRef1EndDate'

present = pd.concat([TPI_Ref_2['ResearchId']])
remaining_df = tpi[~tpi['ResearchId'].isin(present)]

In [2]:
data = remaining_df
data = time_format(data,'DocRef2EndDate','fmt_DocRef2EndDate')
data = time_year(data,'fmt_DocRef2EndDate','year(DocRef2EndDate)')
data = filter_col(data,'Ref2Category','DocRef2Name')

TPI_Ref_3 = group(data,'ResearchCycleId','FTSE_ID','ResearchId','fmt_DocRef2EndDate','year(DocRef2EndDate)')

TPI_Ref_3=TPI_Ref_3.rename(columns={"fmt_DocRef2EndDate": "Date","year(DocRef2EndDate)":"Year(Date)"})
TPI_Ref_3['Method']= 'DocRef2EndDate'

present = pd.concat([TPI_Ref_2['ResearchId'],TPI_Ref_3['ResearchId']])
remaining_df = tpi[~tpi['ResearchId'].isin(present)]

NameError: name 'remaining_df' is not defined

In [ ]:
data = remaining_df
data = time_format(data,'DocRef1FilingDate','fmt_DocRef1FilingDate')
data = time_year(data,'fmt_DocRef1FilingDate','year(DocRef1FilingDate)')
data = filter_col(data,'Ref1Category','DocRef1Name')

TPI_Ref_4 = group(data,'ResearchCycleId','FTSE_ID','ResearchId','fmt_DocRef1FilingDate','year(DocRef1FilingDate)')

TPI_Ref_4=TPI_Ref_4.rename(columns={"fmt_DocRef1FilingDate": "Date","year(DocRef1FilingDate)":"Year(Date)"})

TPI_Ref_4['Method']= 'DocRef1FilingDate - 1'
TPI_Ref_4['Year(Date)']= TPI_Ref_4['Year(Date)']-1

present = pd.concat([  TPI_Ref_2['ResearchId'],TPI_Ref_3['ResearchId'],TPI_Ref_4['ResearchId']])
remaining_df = tpi[~tpi['ResearchId'].isin(present)]

In [ ]:
data = remaining_df
data = time_format(data,'DocRef2FilingDate','fmt_DocRef2FilingDate')
data = time_year(data,'fmt_DocRef2FilingDate','year(DocRef2FilingDate)')
data = filter_col(data,'Ref2Category','DocRef2Name')

TPI_Ref_5 = group(data,'ResearchCycleId','FTSE_ID','ResearchId','fmt_DocRef2FilingDate','year(DocRef2FilingDate)')

TPI_Ref_5=TPI_Ref_5.rename(columns={"fmt_DocRef2FilingDate": "Date","year(DocRef2FilingDate)":"Year(Date)"})

TPI_Ref_5['Method']= 'DocRef2FilingDate - 1'
TPI_Ref_5['Year(Date)']= TPI_Ref_5['Year(Date)']-1

present = pd.concat([TPI_Ref_2['ResearchId'],TPI_Ref_3['ResearchId'], TPI_Ref_4['ResearchId'],TPI_Ref_5['ResearchId']])
remaining_df = df[~df['ResearchId'].isin(present)]

In [18]:
FY_analysis = pd.concat([TPI_Ref_2,TPI_Ref_3,TPI_Ref_4,TPI_Ref_5])
FY_analysis = FY_analysis.rename(columns={0:"Count"})

In [13]:
# date = datetime.today().strftime('%d-%m-%Y')
# location = 'C://Users////r//'    
# file_save = "FY_analysis"+str(date)+".csv"
# FY_analysis.to_csv(location+file_save)

In [19]:
FY_analysis.head(1)

,ResearchCycleId,FTSE_ID,ResearchId,Date,Year(Date),Count,Method
0,9,1369193,43348,2022-03-31,2022.0,2,DocRef1EndDate

In [40]:
FY_analysis[( FY_analysis['ResearchId'] ==26328)]

,ResearchCycleId,FTSE_ID,ResearchId,Date,Year(Date),Count,Method
15315,7,1205310,26328,2019-12-31,2019.0,36,DocRef1EndDate